INSERT INTO system_config (config_key, config_value, description) VALUES
    ('earnings.dailyMinRate', '2.4', '每台设备每天收益最低金额'),
    ('earnings.dailyMaxRate', '2.4', '每台设备每天收益最高金额'),
    ('earnings.maxDailyOfflineHours', '24', '每天累计离线超过该小时数时收益为零'),
    ('earnings.hashratePerYuan', '100', '每元对应的聚芯算力值'),
    ('earnings.minWithdraw', '10', '最低提现金额'),
    ('earnings.withdrawFee', '1', '提现手续费百分比'),
    ('invite.earningsRate', '0.10', '邀请收益分成比例'),
    ('invite.level.count', '5', '代理等级数量'),
    ('invite.level1.name', 'A', '一级名称'),
    ('invite.level1.rate', '0.70', '一级结算比例'),
    ('invite.level1.threshold', '1', '一级团队设备门槛'),
    ('invite.level2.name', 'B', '二级名称'),
    ('invite.level2.rate', '0.80', '二级结算比例'),
    ('invite.level2.threshold', '100', '二级团队设备门槛'),
    ('invite.level3.name', 'C', '三级名称'),
    ('invite.level3.rate', '0.85', '三级结算比例'),
    ('invite.level3.threshold', '300', '三级团队设备门槛'),
    ('invite.level4.name', 'D', '四级名称'),
    ('invite.level4.rate', '0.90', '四级结算比例'),
    ('invite.level4.threshold', '1000', '四级团队设备门槛'),
    ('invite.level5.name', 'E', '五级名称'),
    ('invite.level5.rate', '0.95', '五级结算比例'),
    ('invite.level5.threshold', '3000', '五级团队设备门槛'),
    ('device.heartbeatTimeout', '120', '心跳请求超时时间，单位秒'),
    ('device.heartbeatInterval', '60', 'Agent 心跳上报间隔，单位秒'),
    ('device.taskPollInterval', '15', '计算作业轮询间隔，单位秒'),
    ('device.offlineThreshold', '180', '设备离线判定时间，单位秒'),
    ('device.autoAssignBusiness', 'true', '绑定后自动分配业务号'),
    ('device.initialHashrate', '100', '新设备初始聚芯算力值'),
    ('device.powerMode', 'MAXN_SUPER', '全局 Orin 功耗模式：15W、25W 或 MAXN_SUPER'),
    ('device.upgradeTimeoutMinutes', '30', '设备升级超时时间，单位分钟'),
    ('system.siteName', '聚芯 Orin', '系统名称'),
    ('system.contactEmail', '', '联系邮箱'),
    ('system.contactWechat', 'orin-support', '客服微信'),
    ('system.contactWorkTime', '9:00-18:00', '客服工作时间'),
    ('system.maintenanceMode', 'false', '维护模式'),
    ('system.bannerList', '[]', '小程序轮播图 JSON'),
    ('withdraw.allowedDays', '', '允许提现的星期，空值表示不限')
ON DUPLICATE KEY UPDATE
    config_value = VALUES(config_value),
    description = VALUES(description);
