-- 设备 Agent 在线升级管理
CREATE TABLE IF NOT EXISTS device_upgrade_package (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    package_no VARCHAR(64) NOT NULL COMMENT '升级包编号',
    version VARCHAR(64) NOT NULL COMMENT '目标 Agent 版本',
    file_name VARCHAR(255) NOT NULL COMMENT '原始文件名',
    file_path VARCHAR(500) NOT NULL COMMENT '服务器物理路径',
    file_url VARCHAR(500) NOT NULL COMMENT '设备下载 URL',
    file_size BIGINT DEFAULT 0 COMMENT '文件大小',
    checksum VARCHAR(128) COMMENT 'SHA-256 校验值',
    status VARCHAR(32) DEFAULT 'active' COMMENT 'active/disabled',
    release_note TEXT COMMENT '更新说明',
    uploaded_by VARCHAR(64) COMMENT '上传人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE INDEX uk_package_no (package_no),
    INDEX idx_version (version),
    INDEX idx_status (status),
    INDEX idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备 Agent 升级包';

CREATE TABLE IF NOT EXISTS device_upgrade_batch (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    batch_no VARCHAR(64) NOT NULL COMMENT '升级批次编号',
    package_id BIGINT NOT NULL COMMENT '升级包ID',
    target_version VARCHAR(64) NOT NULL COMMENT '目标版本',
    target_scope VARCHAR(32) NOT NULL COMMENT 'ALL_ONLINE/LOCATION/CARRIER',
    location_keyword VARCHAR(128) COMMENT '地区关键词',
    carrier VARCHAR(64) COMMENT '运营商',
    total_count INT DEFAULT 0,
    pending_count INT DEFAULT 0,
    delivered_count INT DEFAULT 0,
    upgrading_count INT DEFAULT 0,
    success_count INT DEFAULT 0,
    failed_count INT DEFAULT 0,
    skipped_count INT DEFAULT 0,
    status VARCHAR(32) DEFAULT 'running' COMMENT 'running/completed/failed/partial',
    remark VARCHAR(255) COMMENT '备注',
    started_at DATETIME COMMENT '开始时间',
    finished_at DATETIME COMMENT '完成时间',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE INDEX uk_batch_no (batch_no),
    INDEX idx_package_id (package_id),
    INDEX idx_status (status),
    INDEX idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备 Agent 升级批次';

CREATE TABLE IF NOT EXISTS device_upgrade_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    batch_id BIGINT NOT NULL COMMENT '批次ID',
    package_id BIGINT NOT NULL COMMENT '升级包ID',
    command_id BIGINT COMMENT '远程指令ID',
    command_no VARCHAR(64) COMMENT '远程指令编号',
    device_id BIGINT COMMENT '设备ID',
    device_sn VARCHAR(64) NOT NULL COMMENT '设备SN',
    from_version VARCHAR(64) COMMENT '升级前版本',
    target_version VARCHAR(64) NOT NULL COMMENT '目标版本',
    status VARCHAR(32) DEFAULT 'pending' COMMENT 'pending/delivered/upgrading/success/failed/skipped/timeout',
    error_msg VARCHAR(500) COMMENT '失败原因',
    result_text TEXT COMMENT '指令输出摘要',
    delivered_at DATETIME COMMENT '指令回传时间',
    finished_at DATETIME COMMENT '最终完成时间',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_batch_id (batch_id),
    INDEX idx_package_id (package_id),
    INDEX idx_command_no (command_no),
    INDEX idx_device_sn (device_sn),
    INDEX idx_status (status),
    INDEX idx_target_version (target_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备 Agent 单机升级记录';
