SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    nickname VARCHAR(50),
    role VARCHAR(20) NOT NULL DEFAULT 'admin',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_user_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS system_config (
    id BIGINT NOT NULL AUTO_INCREMENT,
    config_key VARCHAR(100) NOT NULL,
    config_value TEXT,
    description VARCHAR(255),
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_system_config_key (config_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS api_merchant (
    id BIGINT NOT NULL AUTO_INCREMENT,
    merchant_name VARCHAR(100) NOT NULL,
    app_id VARCHAR(64) NOT NULL,
    app_secret VARCHAR(255) NOT NULL,
    permissions TEXT,
    status TINYINT NOT NULL DEFAULT 1,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    expire_time DATETIME,
    balance DECIMAL(16,2) NOT NULL DEFAULT 0.00,
    level INT NOT NULL DEFAULT 0,
    contact_phone VARCHAR(32),
    bind_user_id BIGINT,
    PRIMARY KEY (id),
    UNIQUE KEY uk_api_merchant_app_id (app_id),
    KEY idx_api_merchant_bind_user (bind_user_id),
    KEY idx_api_merchant_status (status, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT NOT NULL,
    openid VARCHAR(128) NOT NULL,
    nickname VARCHAR(100),
    avatar_url VARCHAR(500),
    phone VARCHAR(32),
    balance DECIMAL(16,2) NOT NULL DEFAULT 0.00,
    quota INT NOT NULL DEFAULT 0,
    inviter_id BIGINT,
    level INT NOT NULL DEFAULT 0,
    level_manual TINYINT NOT NULL DEFAULT 0,
    wx_qr_code VARCHAR(500),
    ali_qr_code VARCHAR(500),
    bank_name VARCHAR(100),
    bank_card_no VARCHAR(100),
    bank_holder_name VARCHAR(100),
    id_card VARCHAR(32),
    id_card_front VARCHAR(500),
    id_card_back VARCHAR(500),
    alipay_account VARCHAR(100),
    withdraw_disabled TINYINT NOT NULL DEFAULT 0,
    user_type VARCHAR(20) NOT NULL DEFAULT 'personal',
    remark VARCHAR(500),
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    deleted_at DATETIME,
    merchant_id BIGINT,
    external_user_id VARCHAR(100),
    PRIMARY KEY (id),
    UNIQUE KEY uk_app_user_openid (openid),
    KEY idx_app_user_inviter (inviter_id),
    KEY idx_app_user_deleted (deleted, deleted_at),
    KEY idx_app_user_merchant_external (merchant_id, external_user_id),
    KEY idx_app_user_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS device (
    id BIGINT NOT NULL AUTO_INCREMENT,
    sn VARCHAR(64) NOT NULL,
    bind_code VARCHAR(32),
    business_id VARCHAR(64),
    user_id BIGINT,
    merchant_id BIGINT,
    status TINYINT NOT NULL DEFAULT 0,
    ip VARCHAR(64),
    name VARCHAR(100),
    location VARCHAR(160) DEFAULT '未知位置',
    carrier VARCHAR(64),
    hashrate INT NOT NULL DEFAULT 0,
    type TINYINT NOT NULL DEFAULT 2,
    last_heartbeat_time DATETIME,
    last_pay_time DATETIME,
    bind_time DATETIME,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pending_command TEXT,
    cpu_usage VARCHAR(16),
    memory_usage VARCHAR(16),
    cpu_model VARCHAR(255),
    agent_version VARCHAR(64),
    image_version VARCHAR(64),
    device_token_hash CHAR(64),
    device_token_seed CHAR(64),
    hardware_fingerprint VARCHAR(128),
    enrolled_at DATETIME,
    device_model VARCHAR(160),
    architecture VARCHAR(32),
    l4t_version VARCHAR(128),
    cuda_version VARCHAR(32),
    gpu_usage VARCHAR(16),
    gpu_temperature DOUBLE,
    power_watts DOUBLE,
    memory_total_mb INT,
    PRIMARY KEY (id),
    UNIQUE KEY uk_device_sn (sn),
    UNIQUE KEY uk_device_bind_code (bind_code),
    KEY idx_device_user (user_id),
    KEY idx_device_merchant (merchant_id),
    KEY idx_device_status_type (status, type),
    KEY idx_device_heartbeat (last_heartbeat_time),
    UNIQUE KEY uk_device_token_hash (device_token_hash),
    UNIQUE KEY uk_device_hardware_fingerprint (hardware_fingerprint)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS compute_job (
    id BIGINT NOT NULL AUTO_INCREMENT,
    task_id VARCHAR(64) NOT NULL,
    task_type VARCHAR(64) NOT NULL,
    task_params LONGTEXT,
    retry_count INT NOT NULL DEFAULT 0,
    device_sn VARCHAR(64),
    prompt TEXT,
    response_text LONGTEXT,
    model_name VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    generate_tokens INT NOT NULL DEFAULT 0,
    reward_hashrate INT NOT NULL DEFAULT 0,
    duration_ms BIGINT,
    error_msg TEXT,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_compute_job_task_id (task_id),
    KEY idx_compute_job_queue (status, deleted, create_time),
    KEY idx_compute_job_device (device_sn, status),
    KEY idx_compute_job_updated (update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS device_command (
    id BIGINT NOT NULL AUTO_INCREMENT,
    command_no VARCHAR(64) NOT NULL,
    device_id BIGINT,
    device_sn VARCHAR(64) NOT NULL,
    command_type VARCHAR(64) NOT NULL,
    command_text TEXT NOT NULL,
    command_payload TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    exit_code INT,
    result_text LONGTEXT,
    remark VARCHAR(255),
    dispatched_at DATETIME,
    finished_at DATETIME,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_device_command_no (command_no),
    KEY idx_device_command_device (device_sn),
    KEY idx_device_command_status (status),
    KEY idx_device_command_created (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS device_earnings (
    id BIGINT NOT NULL AUTO_INCREMENT,
    device_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    amount DECIMAL(16,2) NOT NULL,
    date DATE NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_device_earnings_device_date (device_id, date, amount),
    KEY idx_device_earnings_user_date (user_id, date, amount),
    KEY idx_device_earnings_date (date, amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS device_offline_log (
    id BIGINT NOT NULL AUTO_INCREMENT,
    device_id BIGINT NOT NULL,
    sn VARCHAR(64),
    bind_code VARCHAR(32),
    offline_time DATETIME,
    last_heartbeat_time DATETIME,
    reason VARCHAR(255),
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_device_offline_device (device_id),
    KEY idx_device_offline_sn (sn),
    KEY idx_device_offline_time (offline_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS device_upgrade_package (
    id BIGINT NOT NULL AUTO_INCREMENT,
    package_no VARCHAR(64) NOT NULL,
    version VARCHAR(64) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_url VARCHAR(500) NOT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    checksum VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    release_note TEXT,
    uploaded_by VARCHAR(64),
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_upgrade_package_no (package_no),
    KEY idx_upgrade_package_version (version),
    KEY idx_upgrade_package_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS device_upgrade_batch (
    id BIGINT NOT NULL AUTO_INCREMENT,
    batch_no VARCHAR(64) NOT NULL,
    package_id BIGINT NOT NULL,
    target_version VARCHAR(64) NOT NULL,
    target_scope VARCHAR(32) NOT NULL,
    location_keyword VARCHAR(128),
    carrier VARCHAR(64),
    total_count INT NOT NULL DEFAULT 0,
    pending_count INT NOT NULL DEFAULT 0,
    delivered_count INT NOT NULL DEFAULT 0,
    upgrading_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    failed_count INT NOT NULL DEFAULT 0,
    skipped_count INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'running',
    remark VARCHAR(255),
    started_at DATETIME,
    finished_at DATETIME,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_upgrade_batch_no (batch_no),
    KEY idx_upgrade_batch_package (package_id),
    KEY idx_upgrade_batch_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS device_upgrade_record (
    id BIGINT NOT NULL AUTO_INCREMENT,
    batch_id BIGINT NOT NULL,
    package_id BIGINT NOT NULL,
    command_id BIGINT,
    command_no VARCHAR(64),
    device_id BIGINT,
    device_sn VARCHAR(64) NOT NULL,
    from_version VARCHAR(64),
    target_version VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    error_msg VARCHAR(500),
    result_text LONGTEXT,
    delivered_at DATETIME,
    finished_at DATETIME,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_upgrade_record_batch (batch_id),
    KEY idx_upgrade_record_package (package_id),
    KEY idx_upgrade_record_command (command_no),
    KEY idx_upgrade_record_device (device_sn),
    KEY idx_upgrade_record_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS notice (
    id BIGINT NOT NULL AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    content TEXT,
    image_url VARCHAR(500),
    type TINYINT NOT NULL DEFAULT 1,
    status TINYINT NOT NULL DEFAULT 0,
    sort INT NOT NULL DEFAULT 0,
    publish_time DATETIME,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_notice_status (status, sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS invite_reward (
    id BIGINT NOT NULL AUTO_INCREMENT,
    inviter_id BIGINT NOT NULL,
    invitee_id BIGINT NOT NULL,
    reward DECIMAL(16,2) NOT NULL DEFAULT 0.00,
    reward_type VARCHAR(32) NOT NULL DEFAULT 'earnings',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    device_id BIGINT,
    remark VARCHAR(255),
    PRIMARY KEY (id),
    KEY idx_invite_reward_inviter (inviter_id),
    KEY idx_invite_reward_invitee (invitee_id),
    KEY idx_invite_reward_device (device_id),
    KEY idx_invite_reward_sum (inviter_id, reward_type, reward),
    KEY idx_invite_reward_time (inviter_id, reward_type, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_feedback (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT,
    type VARCHAR(32) NOT NULL,
    content TEXT NOT NULL,
    contact VARCHAR(100),
    images TEXT,
    status TINYINT NOT NULL DEFAULT 0,
    reply TEXT,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_user_feedback_user (user_id),
    KEY idx_user_feedback_status (status),
    KEY idx_user_feedback_created (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_address (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    receiver_name VARCHAR(50) NOT NULL,
    phone VARCHAR(32) NOT NULL,
    province VARCHAR(50),
    city VARCHAR(50),
    district VARCHAR(50),
    detail_address VARCHAR(300) NOT NULL,
    is_default TINYINT NOT NULL DEFAULT 0,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_user_address_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS exchange_product (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    image_url VARCHAR(500),
    images TEXT,
    base_price DECIMAL(16,2) NOT NULL,
    price_level1 DECIMAL(16,2),
    price_level2 DECIMAL(16,2),
    price_level3 DECIMAL(16,2),
    price_level4 DECIMAL(16,2),
    price_level5 DECIMAL(16,2),
    stock INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_exchange_product_status (status, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS exchange_order (
    id BIGINT NOT NULL AUTO_INCREMENT,
    order_no VARCHAR(32) NOT NULL,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(100),
    product_image VARCHAR(500),
    quantity INT NOT NULL DEFAULT 1,
    unit_price DECIMAL(16,2) NOT NULL,
    total_price DECIMAL(16,2) NOT NULL,
    hashrate_cost BIGINT NOT NULL,
    user_level INT,
    receiver_name VARCHAR(50),
    receiver_phone VARCHAR(32),
    receiver_address VARCHAR(500),
    status TINYINT NOT NULL DEFAULT 0,
    express_company VARCHAR(50),
    express_no VARCHAR(100),
    ship_time DATETIME,
    receive_time DATETIME,
    remark VARCHAR(255),
    admin_remark VARCHAR(255),
    inviter_id BIGINT,
    inviter_level INT,
    inviter_profit DECIMAL(16,2) NOT NULL DEFAULT 0.00,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_exchange_order_no (order_no),
    KEY idx_exchange_order_user (user_id),
    KEY idx_exchange_order_status (status),
    KEY idx_exchange_order_created (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS exchange_logistics (
    id BIGINT NOT NULL AUTO_INCREMENT,
    order_id BIGINT NOT NULL,
    status TINYINT NOT NULL,
    description VARCHAR(255),
    operator VARCHAR(50),
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_exchange_logistics_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_contract (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    real_name VARCHAR(50) NOT NULL,
    id_card VARCHAR(32) NOT NULL,
    mobile VARCHAR(32) NOT NULL,
    bank_card_no VARCHAR(100),
    alipay_account VARCHAR(100),
    status TINYINT NOT NULL DEFAULT 0,
    provider_id VARCHAR(64) NOT NULL,
    payment_type TINYINT NOT NULL DEFAULT 0,
    contract_time DATETIME,
    fail_reason VARCHAR(255),
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_contract_provider (user_id, provider_id),
    KEY idx_user_contract_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_payment_apply (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    old_info VARCHAR(1000),
    payment_type TINYINT NOT NULL DEFAULT 0,
    new_card_no VARCHAR(100) NOT NULL,
    status TINYINT NOT NULL DEFAULT 0,
    reject_reason VARCHAR(255),
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_payment_apply_user (user_id),
    KEY idx_payment_apply_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS withdraw (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    amount DECIMAL(16,2) NOT NULL,
    fee DECIMAL(16,2) NOT NULL DEFAULT 0.00,
    actual_amount DECIMAL(16,2) NOT NULL,
    type TINYINT NOT NULL DEFAULT 1,
    account VARCHAR(100),
    real_name VARCHAR(100),
    qr_code VARCHAR(500),
    status TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500),
    boss_kg_batch_id VARCHAR(64),
    boss_kg_order_no VARCHAR(64),
    boss_kg_state TINYINT,
    boss_kg_fee DECIMAL(16,2),
    boss_kg_user_fee DECIMAL(16,2),
    boss_kg_actual_amount DECIMAL(16,2),
    boss_kg_failed TINYINT NOT NULL DEFAULT 0,
    payment_fail_count INT NOT NULL DEFAULT 0,
    id_card VARCHAR(32),
    mobile VARCHAR(32),
    bank_card_no VARCHAR(100),
    alipay_account VARCHAR(100),
    reject_reason VARCHAR(255),
    process_time DATETIME,
    auditor_id BIGINT,
    audit_time DATETIME,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_withdraw_user (user_id),
    KEY idx_withdraw_status (status),
    KEY idx_withdraw_boss_kg_batch (boss_kg_batch_id),
    KEY idx_withdraw_boss_kg_order (boss_kg_order_no),
    KEY idx_withdraw_created (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
