CREATE TABLE IF NOT EXISTS app_user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20) NOT NULL UNIQUE,
    nickname VARCHAR(40) NOT NULL DEFAULT 'Orin 用户',
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sms_login_challenge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20) NOT NULL,
    code_hash CHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP NULL,
    attempts INT NOT NULL DEFAULT 0,
    client_ip VARCHAR(64) NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    provider_request_id VARCHAR(128) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sms_challenge_phone_created ON sms_login_challenge(phone, created_at);
CREATE INDEX IF NOT EXISTS idx_sms_challenge_ip_created ON sms_login_challenge(client_ip, created_at);
CREATE INDEX IF NOT EXISTS idx_sms_challenge_active ON sms_login_challenge(phone, consumed_at, expires_at);

CREATE TABLE IF NOT EXISTS app_node (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    binding_code VARCHAR(64) NOT NULL UNIQUE,
    owner_user_id BIGINT NULL,
    name VARCHAR(80) NOT NULL DEFAULT 'Orin 节点',
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    hashrate DECIMAL(18,3) NOT NULL DEFAULT 0,
    temperature DECIMAL(6,2) NULL,
    daily_earnings DECIMAL(18,8) NOT NULL DEFAULT 0,
    total_earnings DECIMAL(18,8) NOT NULL DEFAULT 0,
    last_reported_at TIMESTAMP NULL,
    bound_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_app_node_owner ON app_node(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_app_node_owner_status ON app_node(owner_user_id, status);
CREATE INDEX IF NOT EXISTS idx_app_node_last_reported ON app_node(last_reported_at);
