CREATE TABLE IF NOT EXISTS app_user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20) NOT NULL UNIQUE,
    nickname VARCHAR(40) NOT NULL DEFAULT '聚芯用户',
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sms_login_challenge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20) NOT NULL,
    code_hash CHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP NULL,
    attempts INT NOT NULL DEFAULT 0,
    client_ip VARCHAR(64) NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    provider_request_id VARCHAR(128) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sms_challenge_phone_created ON sms_login_challenge(phone, created_at);
CREATE INDEX IF NOT EXISTS idx_sms_challenge_ip_created ON sms_login_challenge(client_ip, created_at);
CREATE INDEX IF NOT EXISTS idx_sms_challenge_active ON sms_login_challenge(phone, consumed_at, expires_at);

CREATE TABLE IF NOT EXISTS app_node (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    binding_code VARCHAR(64) NOT NULL UNIQUE,
    owner_user_id BIGINT NULL,
    name VARCHAR(80) NOT NULL DEFAULT '聚芯节点',
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    hashrate DECIMAL(18,3) NOT NULL DEFAULT 0,
    temperature DECIMAL(6,2) NULL,
    daily_earnings DECIMAL(18,8) NOT NULL DEFAULT 0,
    total_earnings DECIMAL(18,8) NOT NULL DEFAULT 0,
    last_reported_at TIMESTAMP NULL,
    bound_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_edge_device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_sn VARCHAR(64) NOT NULL UNIQUE,
    binding_code VARCHAR(64) NOT NULL UNIQUE,
    device_token_hash CHAR(64) NOT NULL,
    hardware_fingerprint CHAR(64),
    agent_version VARCHAR(64),
    image_version VARCHAR(128),
    telemetry_json CLOB,
    last_reported_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_app_edge_device_last_reported ON app_edge_device(last_reported_at);

CREATE TABLE IF NOT EXISTS app_edge_command (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_no VARCHAR(64) NOT NULL UNIQUE,
    device_sn VARCHAR(64) NOT NULL,
    command_type VARCHAR(32) NOT NULL,
    command_text VARCHAR(512) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    exit_code INT NULL,
    result_text CLOB NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_app_edge_command_device_status
    ON app_edge_command(device_sn, status, created_at);

CREATE INDEX IF NOT EXISTS idx_app_node_owner ON app_node(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_app_node_owner_status ON app_node(owner_user_id, status);
CREATE INDEX IF NOT EXISTS idx_app_node_last_reported ON app_node(last_reported_at);

CREATE TABLE IF NOT EXISTS app_mobile_release (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, platform VARCHAR(16) NOT NULL DEFAULT 'android', version VARCHAR(64) NOT NULL, version_code INT NOT NULL, file_name VARCHAR(255) NOT NULL, file_size BIGINT NOT NULL, sha256 CHAR(64) NOT NULL, release_note CLOB, force_update BOOLEAN NOT NULL DEFAULT FALSE, status VARCHAR(16) NOT NULL DEFAULT 'active', storage_path VARCHAR(500) NOT NULL, download_path VARCHAR(500) NOT NULL, published_at TIMESTAMP, created_by VARCHAR(80) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS app_admin_audit_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, admin_username VARCHAR(80) NOT NULL, action VARCHAR(80) NOT NULL, resource_type VARCHAR(40) NOT NULL, resource_id VARCHAR(80), detail CLOB, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_app_admin_audit_created ON app_admin_audit_log(created_at);
CREATE TABLE IF NOT EXISTS app_earning_record (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, node_id BIGINT, amount DECIMAL(18,8) NOT NULL, earning_date DATE NOT NULL, source VARCHAR(40) NOT NULL DEFAULT 'node', description VARCHAR(255), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_app_earning_user_date ON app_earning_record(user_id, earning_date);
CREATE TABLE IF NOT EXISTS app_wallet_ledger (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, amount DECIMAL(18,8) NOT NULL, balance_after DECIMAL(18,8) NOT NULL, direction VARCHAR(12) NOT NULL, entry_type VARCHAR(32) NOT NULL, idempotency_key VARCHAR(100) NOT NULL UNIQUE, description VARCHAR(255), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_app_wallet_user_created ON app_wallet_ledger(user_id, created_at);
CREATE TABLE IF NOT EXISTS app_withdrawal (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, amount DECIMAL(18,8) NOT NULL, method VARCHAR(24) NOT NULL, account_name VARCHAR(80), account_no VARCHAR(128), status VARCHAR(20) NOT NULL DEFAULT 'pending', review_note VARCHAR(255), reviewed_by VARCHAR(80), reviewed_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_app_withdrawal_status_created ON app_withdrawal(status, created_at);
CREATE TABLE IF NOT EXISTS app_payment_apply (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, method VARCHAR(24) NOT NULL, account_name VARCHAR(80) NOT NULL, account_no VARCHAR(128) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', review_note VARCHAR(255), reviewed_by VARCHAR(80), reviewed_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_app_payment_status_created ON app_payment_apply(status, created_at);
CREATE TABLE IF NOT EXISTS app_notice (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(160) NOT NULL, content CLOB NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'draft', pinned BOOLEAN NOT NULL DEFAULT FALSE, published_at TIMESTAMP, created_by VARCHAR(80) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_app_notice_status_created ON app_notice(status, created_at);
CREATE TABLE IF NOT EXISTS app_feedback (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, category VARCHAR(40), content CLOB NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'open', reply CLOB, handled_by VARCHAR(80), handled_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_app_feedback_status_created ON app_feedback(status, created_at);
CREATE TABLE IF NOT EXISTS app_invite_relation (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, inviter_user_id BIGINT NOT NULL, invitee_user_id BIGINT NOT NULL UNIQUE, invite_code VARCHAR(40) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_app_inviter ON app_invite_relation(inviter_user_id);
CREATE TABLE IF NOT EXISTS app_reward_record (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, source_user_id BIGINT, amount DECIMAL(18,8) NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'settled', description VARCHAR(255), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_app_reward_user_created ON app_reward_record(user_id, created_at);
CREATE TABLE IF NOT EXISTS app_exchange_product (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(160) NOT NULL, description CLOB, price DECIMAL(18,8) NOT NULL, stock INT NOT NULL DEFAULT 0, status VARCHAR(16) NOT NULL DEFAULT 'active', image_url VARCHAR(500), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_app_exchange_product_status ON app_exchange_product(status);
CREATE TABLE IF NOT EXISTS app_exchange_order (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_no VARCHAR(48) NOT NULL UNIQUE, user_id BIGINT NOT NULL, product_id BIGINT NOT NULL, quantity INT NOT NULL DEFAULT 1, amount DECIMAL(18,8) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', address_snapshot CLOB, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_app_exchange_order_status ON app_exchange_order(status, created_at);
CREATE TABLE IF NOT EXISTS app_exchange_logistics (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id BIGINT NOT NULL UNIQUE, carrier VARCHAR(80) NOT NULL, tracking_no VARCHAR(100) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'shipped', shipped_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS app_device_task (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_no VARCHAR(48) NOT NULL UNIQUE, device_sn VARCHAR(64), task_type VARCHAR(40) NOT NULL, payload CLOB, status VARCHAR(20) NOT NULL DEFAULT 'pending', result_text CLOB, created_by VARCHAR(80) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_app_device_task_status ON app_device_task(status, created_at);
CREATE TABLE IF NOT EXISTS app_device_upgrade_package (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version VARCHAR(64) NOT NULL, file_name VARCHAR(255) NOT NULL, download_url VARCHAR(500) NOT NULL, sha256 CHAR(64) NOT NULL, release_note CLOB, status VARCHAR(16) NOT NULL DEFAULT 'active', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_app_upgrade_package_version ON app_device_upgrade_package(version);
CREATE TABLE IF NOT EXISTS app_device_upgrade_record (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, package_id BIGINT NOT NULL, device_sn VARCHAR(64) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', result_text CLOB, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_app_upgrade_record_status ON app_device_upgrade_record(status, created_at);
CREATE TABLE IF NOT EXISTS app_system_setting (setting_key VARCHAR(80) PRIMARY KEY, setting_value CLOB NOT NULL, updated_by VARCHAR(80) NOT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
